/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Task_1_StudentGradeTracker;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class StudentGradeTracker extends javax.swing.JFrame {

    // Declare the ArrayList at the class level
    private ArrayList<Student> students;
    
    /**
     * Creates new form StudentGradeTracker
     */
    
    public StudentGradeTracker() {
        initComponents();
        
        students = new ArrayList<>(); // Initialize the ArrayList to store Student objects
    }

      // Inner class to represent a Student
    class Student {
        String name;
        int grade;
        
        public Student(String name, int grade) {
            this.name = name;
            this.grade = grade;
        }
        
        public String toString() {
            return name +": "+ grade;
        }
    }
    
    // Method to add a student
    public void addStudent() {
        String name = txtName.getText().trim(); // trim remove any leading or trailing whitespace
        String grade = txtGrade.getText().trim();
        
        // Validate input
        if(name.isEmpty() || grade.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter both name and grade.");
            return;  // Exit the method if validation fails
        }
        
        // Try-catch: Catches invalid grade input and shows an error message.
        try{
           int g = Integer.parseInt(grade); 
           
           // Create a new Student object and add it to the ArrayList
           students.add(new Student(name,g));
           
            // Display the student's info in the JTextArea
            studentDisplay.append(name +": "+ g +"\n");
            
            JOptionPane.showMessageDialog(this, "Data Added.");
            // Display the student's info in the studentDisplay
            txtName.setText(null);
            txtGrade.setText(null);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter a valid number for grade.");
        }
    }
    
    // method to calculate the average, highest, and lowest grades
    public void calculateGrade() {
        if(students.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No students available to calculate.");
            return;
        }
        
        int sum = 0;
        int highGrade = Integer.MIN_VALUE; // Initialize highest to the smallest possible value
        int lowGrade = Integer.MAX_VALUE;  // Initialize lowest to the largest possible value
        
        // Iterate over the ArrayList to calculate
        for(Student student : students) {
            int grade = student.grade; // grade field of the Student object is used to compute
            sum += grade;
            if(grade > highGrade) highGrade = grade;
            if(grade < lowGrade) lowGrade = grade;
        }
        
        int average = sum / students.size();
        
        // display grades analysis in gradeAnalysis
        gradeAnalysis.setText(""); // Clear previous analysis
        gradeAnalysis.append("Average: " + average + "\n");
        gradeAnalysis.append("Highest: " + highGrade + "\n");
        gradeAnalysis.append("Lowest: " + lowGrade + "\n");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        txtGrade = new app.bolivia.swing.JCTextField();
        txtName = new app.bolivia.swing.JCTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        gradeAnalysis = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        studentDisplay = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Grade Tracker Interface");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(54, 69, 79));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 253, 239));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(64, 64, 64));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Task_1_StudentGradeTracker/icons8_Edit_Property_50px.png"))); // NOI18N
        jLabel1.setText("  STUDENT GRADE TRACKER");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 610, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 70));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Task_1_StudentGradeTracker/icons8_Collaborator_Male_26px.png"))); // NOI18N
        jLabel2.setText(" Student Name :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 160, 40));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Task_1_StudentGradeTracker/icons8_Moleskine_26px.png"))); // NOI18N
        jLabel3.setText("  Enter Grade :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 160, 40));

        jPanel3.setBackground(new java.awt.Color(102, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 1250, 5));

        jLabel4.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Task_1_StudentGradeTracker/icons8_View_Details_26px.png"))); // NOI18N
        jLabel4.setText("  Grade Analysis :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 310, 40));

        btnAdd.setBackground(new java.awt.Color(0, 77, 77));
        btnAdd.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("ADD ");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 180, 140, 30));

        btnCalculate.setBackground(new java.awt.Color(0, 77, 77));
        btnCalculate.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCalculate.setForeground(new java.awt.Color(255, 255, 255));
        btnCalculate.setText("CALCULATE");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 160, 30));

        txtGrade.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        txtGrade.setPlaceholder("Enter student grade.....");
        jPanel1.add(txtGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 360, 40));

        txtName.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        txtName.setPlaceholder("Enter student name.....");
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 360, 40));

        jLabel7.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Task_1_StudentGradeTracker/icons8_Conference_26px.png"))); // NOI18N
        jLabel7.setText("  Student Information :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 310, 40));

        gradeAnalysis.setColumns(20);
        gradeAnalysis.setFont(new java.awt.Font("Sitka Subheading", 1, 18)); // NOI18N
        gradeAnalysis.setRows(5);
        jScrollPane2.setViewportView(gradeAnalysis);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 520, 330, 110));

        studentDisplay.setColumns(20);
        studentDisplay.setFont(new java.awt.Font("Sitka Subheading", 1, 18)); // NOI18N
        studentDisplay.setRows(5);
        jScrollPane3.setViewportView(studentDisplay);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 330, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1273, 650));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        System.exit(0); // to close windows
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        addStudent(); // calling method
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        calculateGrade(); // calling method
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentGradeTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentGradeTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentGradeTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentGradeTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentGradeTracker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JTextArea gradeAnalysis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea studentDisplay;
    private app.bolivia.swing.JCTextField txtGrade;
    private app.bolivia.swing.JCTextField txtName;
    // End of variables declaration//GEN-END:variables
}
