/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Task_3_HotelReservationSystem;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author dell
 */
public class HotelSignUp extends javax.swing.JFrame {

    /**
     * Creates new form HotelSignUp
     */
    public HotelSignUp() {
        initComponents();
        
        // add placeHolderStyle
        addPlaceHolderStyle(txtPswrd);
        addPlaceHolderStyle(txtVerifyPswrd);
    }

    // methods to add and remove place holder style
    public void addPlaceHolderStyle(JTextField textField) {
      Font font = textField.getFont();
      font = font.deriveFont(Font.BOLD);
      textField.setFont(font);
      textField.setForeground(Color.gray);
    }
    
    public void removePlaceHolderStyle(JTextField textField) {
      Font font = textField.getFont();
      font = font.deriveFont(Font.PLAIN|Font.BOLD);
      textField.setFont(font);
      textField.setForeground(Color.black);
    }
    
    // method to insert values into users table
public void insertSignUpDetails() {
    String name = txtName.getText();
    String pwd = txtPswrd.getText();
    String verifyPwd = txtVerifyPswrd.getText(); 
    String email = txtEmail.getText();
    String contact = txtContact.getText();
    
    if (!pwd.equals(verifyPwd)) {
        JOptionPane.showMessageDialog(this, "Passwords do not match. Please try again.");
        return; // Exit the method to prevent further execution
    }
    
    if (checkDuplicateUser(name, email)) {
        JOptionPane.showMessageDialog(this, "User with this name or email already exists.");
        return;
    }
    
    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel_Reservation_System", "root", "programmer._.2004");
        String sql = "insert into users(name, password, email, contact) values(?,?,?,?)";
        PreparedStatement pst = con.prepareStatement(sql);
        
        pst.setString(1, name);
        pst.setString(2, pwd);
        pst.setString(3, email);
        pst.setString(4, contact);
        
        int updatedRowCount = pst.executeUpdate();
        
        if (updatedRowCount > 0) {
            JOptionPane.showMessageDialog(this, "Thank you! Your record has been successfully submitted.");
            HotelLogin login = new HotelLogin();
            login.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Record insertion unsuccessful.");
        }

    } catch (Exception e) {
        e.printStackTrace(); // Prints the stack trace for debugging
    }
}

   // method to check for duplicate users based on name or email
   public Boolean checkDuplicateUser(String name, String email) {
    Boolean isExist = false;
    
    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel_Reservation_System", "root", "programmer._.2004");
        String sql = "select * from users where name = ? OR email = ?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, name);
        pst.setString(2, email);
        ResultSet rs = pst.executeQuery();
        
        if (rs.next()) {
            isExist = true;
        } else {
            isExist = false;
        }
    } catch (Exception e) {
        e.printStackTrace();
    }  
    return isExist;
}

        // method for validation of sign up page
        public Boolean validateSignup() {
        String name = txtName.getText();
        String pwd = txtPswrd.getText();
        String email = txtEmail.getText();
        String contact = txtContact.getText();
        String verifyPwd = txtVerifyPswrd.getText();

        if(name.equals("")){
        JOptionPane.showMessageDialog(this, "Please enter username");
        return false;
        }
         if(pwd.equals("")){
        JOptionPane.showMessageDialog(this, "Please enter password");
        return false;
        }
          if(email.equals("")){
        JOptionPane.showMessageDialog(this, "Please enter email address");
        return false;
        }
           if(contact.equals("")){
        JOptionPane.showMessageDialog(this, "Please enter contact number");
        return false;
        }
            if(verifyPwd.equals("")){
        JOptionPane.showMessageDialog(this, "Please verify your password");
        return false;
        }
        
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new app.bolivia.swing.JCTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new app.bolivia.swing.JCTextField();
        jLabel10 = new javax.swing.JLabel();
        txtVerifyPswrd = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        txtContact = new app.bolivia.swing.JCTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPswrd = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 51, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Algerian", 1, 22)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText(" - The Ultimate Hotel Reservation Experience ");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 590, 50));

        jLabel16.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Welcome to EliteReservations ");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(242, 242, 242));
        jLabel17.setText("X");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 0, 20, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 100));

        jLabel1.setBackground(new java.awt.Color(34, 34, 34));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Task_3_HotelReservationSystem/icons8_Account_50px.png"))); // NOI18N
        jLabel1.setText("FULL NAME :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, -1, -1));

        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(34, 34, 34), 2));
        txtName.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        txtName.setPlaceholder("Enter full name...");
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 120, 300, 40));

        jButton1.setBackground(new java.awt.Color(128, 0, 128));
        jButton1.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SIGN UP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 460, -1, -1));

        jPanel3.setBackground(new java.awt.Color(102, 51, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contact Us: support@elitereservations.com | +92-300-1234567");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Follow Us:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Facebook: facebook.com/EliteReservations");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Twitter: twitter.com/EliteReservations");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Instagram: instagram.com/EliteReservations");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel7.setText("© 2024 EliteReservations. All rights reserved.");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 60, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 1290, 90));

        jLabel8.setBackground(new java.awt.Color(34, 34, 34));
        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Task_3_HotelReservationSystem/icons8_Secured_Letter_50px.png"))); // NOI18N
        jLabel8.setText("  EMAIL :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, -1, -1));

        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(34, 34, 34), 2));
        txtEmail.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        txtEmail.setPlaceholder("Enter email example@gmail.com...");
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 180, 300, 40));

        jLabel10.setBackground(new java.awt.Color(34, 34, 34));
        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Task_3_HotelReservationSystem/verification (1).png"))); // NOI18N
        jLabel10.setText("VERIFY PASSWORD :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 220, 50));

        txtVerifyPswrd.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        txtVerifyPswrd.setText("Re-enter your password...");
        txtVerifyPswrd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(34, 34, 34), 2));
        txtVerifyPswrd.setEchoChar('\u0000');
        txtVerifyPswrd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVerifyPswrdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVerifyPswrdFocusLost(evt);
            }
        });
        txtVerifyPswrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVerifyPswrdActionPerformed(evt);
            }
        });
        jPanel1.add(txtVerifyPswrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 310, 300, 40));

        jLabel11.setBackground(new java.awt.Color(34, 34, 34));
        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Task_3_HotelReservationSystem/icons8_Google_Mobile_50px.png"))); // NOI18N
        jLabel11.setText("PHONE NUMBER :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 370, -1, -1));

        txtContact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(34, 34, 34), 2));
        txtContact.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        txtContact.setPlaceholder("Enter phone number...");
        jPanel1.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 380, 300, 40));

        jLabel12.setBackground(new java.awt.Color(34, 34, 34));
        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Task_3_HotelReservationSystem/icons8_Secure_50px.png"))); // NOI18N
        jLabel12.setText(" PASSWORD :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, -1, -1));

        txtPswrd.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        txtPswrd.setText("Enter password...");
        txtPswrd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(34, 34, 34), 2));
        txtPswrd.setEchoChar('\u0000');
        txtPswrd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPswrdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPswrdFocusLost(evt);
            }
        });
        txtPswrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPswrdActionPerformed(evt);
            }
        });
        jPanel1.add(txtPswrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 240, 300, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Task_3_HotelReservationSystem/hotel (1).jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 660, 350));

        jPanel4.setBackground(new java.awt.Color(152, 103, 164));

        jLabel13.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel13.setText("Where Luxury Meets Convenience");

        jLabel14.setFont(new java.awt.Font("Serif", 1, 27)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Create Your Account at EliteReservations: ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 660, 130));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Already have an account? Log in here.");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel18))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 510, 260, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(1284, 659));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtVerifyPswrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVerifyPswrdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVerifyPswrdActionPerformed

    private void txtPswrdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPswrdFocusGained
        // TODO add your handling code here:
        if(txtPswrd.getText().equals("Enter password...")) {
            txtPswrd.setText(null);
            txtPswrd.requestFocus();
            // set password character
            txtPswrd.setEchoChar('*');
            // remove placeHolderStyle
            removePlaceHolderStyle(txtPswrd);
        }
    }//GEN-LAST:event_txtPswrdFocusGained

    private void txtPswrdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPswrdFocusLost
        // TODO add your handling code here:
        if(txtPswrd.getText().length()==0) {
            addPlaceHolderStyle(txtPswrd);
            txtPswrd.setText("Enter password...");
            txtPswrd.setEchoChar('\u0000');
        }
    }//GEN-LAST:event_txtPswrdFocusLost

    private void txtPswrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPswrdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPswrdActionPerformed

    private void txtVerifyPswrdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVerifyPswrdFocusGained
        // TODO add your handling code here:
        if (txtVerifyPswrd.getText().equals("Re-enter your password...")) {
            txtVerifyPswrd.setText(null);
            txtVerifyPswrd.requestFocus();
            // set password character
            txtVerifyPswrd.setEchoChar('*');
            // remove placeHolderStyle
            removePlaceHolderStyle(txtVerifyPswrd);
        }
    }//GEN-LAST:event_txtVerifyPswrdFocusGained

    private void txtVerifyPswrdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVerifyPswrdFocusLost
        // TODO add your handling code here:
         if(txtVerifyPswrd.getText().length()==0) {
            addPlaceHolderStyle(txtPswrd);
            txtVerifyPswrd.setText("Re-enter your password...");
            txtVerifyPswrd.setEchoChar('\u0000');
        }
    }//GEN-LAST:event_txtVerifyPswrdFocusLost

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        String name = txtName.getText();
        String email = txtEmail.getText(); // Also fetch email to use in checkDuplicateUser

        if (!name.isEmpty()) {
            if (checkDuplicateUser(name, email)) {
                JOptionPane.showMessageDialog(null, "Username or Email already exists");
                txtName.requestFocus(); // Set focus back to the name field
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // if validation is true then signup
   if (validateSignup() == true) {
    String name = txtName.getText();
    String email = txtEmail.getText();

    if (checkDuplicateUser(name, email) == false) {
        insertSignUpDetails();
    } else {
        JOptionPane.showMessageDialog(this, "Username or Email already exists");
    }
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // TODO add your handling code here:
        String name = txtName.getText();
        String email = txtEmail.getText();

        if (!email.isEmpty()) {
            if (checkDuplicateUser(name, email)) {
                JOptionPane.showMessageDialog(null, "Username or Email already exists");
                txtEmail.requestFocus(); // Set focus back to the email field
            }
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
          HotelLogin pg = new  HotelLogin();
        pg.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel18MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private app.bolivia.swing.JCTextField txtContact;
    private app.bolivia.swing.JCTextField txtEmail;
    private app.bolivia.swing.JCTextField txtName;
    private javax.swing.JPasswordField txtPswrd;
    private javax.swing.JPasswordField txtVerifyPswrd;
    // End of variables declaration//GEN-END:variables
}
