/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Task_3_HotelReservationSystem;

import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Statement;
/**
 *
 * @author dell
 */
public class Room extends javax.swing.JFrame {
    
    

    /**
     * Creates new form Room
     */
    public Room() {
        initComponents();
        
        setRoomsDataToTable();
    }
      
     DefaultTableModel model;
    public void setRoomsDataToTable() {
        try {
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel_Reservation_System", "root", "programmer._.2004");
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery("select * from rooms");
             
             while(rs.next()) {
                String roomId = rs.getString("room_id");
                String roomNumber = rs.getString("room_number");
                String roomType = rs.getString("room_type");
                String price = rs.getString("price_per_night");
                String status = rs.getString("availability_status");
                
                Object obj[] = {roomId, roomNumber, roomType, price, status};
                model = (DefaultTableModel) tblRoom.getModel();
                model.addRow(obj);
                
             }
        }catch (Exception e) {
               e.printStackTrace();
            }
    }

      // validate room type combo box 
    private boolean validateRoomType() {
    String selectedRoomType = (String) cbRoomType.getSelectedItem();
    
    if (selectedRoomType == null || selectedRoomType.trim().isEmpty() || selectedRoomType.equals("Select Room type...")) {
        JOptionPane.showMessageDialog(null, "Please select a room type.");
        return false;
    }
    return true;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbRoomType = new javax.swing.JComboBox<>();
        btnAvailableRooms = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRoom = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        txtRoomNumber = new app.bolivia.swing.JCTextField();
        txtRoomType = new app.bolivia.swing.JCTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnBookNow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(102, 51, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(242, 242, 242));
        jLabel17.setText("X");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 0, 20, 30));

        jLabel16.setFont(new java.awt.Font("Bodoni MT Black", 1, 35)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Find Your Perfect Room");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("Search our available rooms and choose the ideal stay for your needs!");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        jPanel11.setBackground(new java.awt.Color(64, 64, 64));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Serif", 1, 17)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Task_3_HotelReservationSystem/icons8_Rewind_48px.png"))); // NOI18N
        jLabel18.setText("  Back");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 40));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(152, 103, 164));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("ROOM TYPE :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        cbRoomType.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        cbRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Room type...", "Single", "Double", "Suite", " " }));
        jPanel3.add(cbRoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 220, 30));

        btnAvailableRooms.setBackground(new java.awt.Color(132, 34, 102));
        btnAvailableRooms.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        btnAvailableRooms.setText("SHOW ALL AVAILABLE ROOMS");
        btnAvailableRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvailableRoomsActionPerformed(evt);
            }
        });
        jPanel3.add(btnAvailableRooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, -1, -1));

        btnSearch.setBackground(new java.awt.Color(132, 34, 102));
        btnSearch.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        btnSearch.setText("SEARCH ");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel3.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1290, 120));

        tblRoom.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tblRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ROOM ID", "ROOM NUMBER", "ROOM TYPE", "PRICE PER NIGHT", "STATUS"
            }
        ));
        tblRoom.setRowHeight(30);
        tblRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRoomMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRoom);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 1030, 280));

        jPanel4.setBackground(new java.awt.Color(152, 103, 164));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRoomNumber.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel4.add(txtRoomNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        txtRoomType.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel4.add(txtRoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("ROOM Type :");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("ROOM Number :");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        btnBookNow.setBackground(new java.awt.Color(132, 34, 102));
        btnBookNow.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        btnBookNow.setText("BOOK NOW");
        btnBookNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookNowActionPerformed(evt);
            }
        });
        jPanel4.add(btnBookNow, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 40, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 1290, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        setSize(new java.awt.Dimension(1288, 682));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        HotelHomePage home = new HotelHomePage();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel11MouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
       if (validateRoomType()) {
        String selectedRoomType = (String) cbRoomType.getSelectedItem();
        
        // Clear the table
        DefaultTableModel model = (DefaultTableModel) tblRoom.getModel();
        model.setRowCount(0);
        
        // Query database and populate table
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel_Reservation_System", "root", "programmer._.2004");
             PreparedStatement stmt = con.prepareStatement("SELECT * FROM rooms WHERE room_type = ? AND availability_status = 'Available'")) {
            stmt.setString(1, selectedRoomType);
            ResultSet rs = stmt.executeQuery();
            
            boolean roomsFound = false; // Flag to check if any rooms are found
            
            while (rs.next()) {
                // Fetch room details from result set
                String roomId = rs.getString("room_id");
                String roomNumber = rs.getString("room_number");
                String roomType = rs.getString("room_type");
                String price = rs.getString("price_per_night");
                String status = rs.getString("availability_status");
                
                Object[] row = { roomId, roomNumber, roomType, price, status };
                model.addRow(row);
                
                roomsFound = true; // Set flag to true if at least one room is found
            }
            
            if (!roomsFound) {
                JOptionPane.showMessageDialog(this, "No rooms available for the selected type.", "No Results", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "An error occurred while retrieving data.", "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAvailableRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvailableRoomsActionPerformed
       // Clear the table
    DefaultTableModel model = (DefaultTableModel) tblRoom.getModel();
    model.setRowCount(0);
    
    // Query database and populate table
    try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel_Reservation_System", "root", "programmer._.2004");
         PreparedStatement stmt = con.prepareStatement("SELECT * FROM rooms WHERE availability_status = 'Available'")) {
        ResultSet rs = stmt.executeQuery();
        
        while(rs.next()) {
                String roomId = rs.getString("room_id");
                String roomNumber = rs.getString("room_number");
                String roomType = rs.getString("room_type");
                String price = rs.getString("price_per_night");
                String status = rs.getString("availability_status");
                
                
                Object obj[] = {roomId, roomNumber, roomType, price, status};
                model = (DefaultTableModel) tblRoom.getModel();
                model.addRow(obj);
                
             }
        } catch (SQLException e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnAvailableRoomsActionPerformed

    private void tblRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRoomMouseClicked
        int selectedRow = tblRoom.getSelectedRow();
    if (selectedRow >= 0) {
        String roomNumber = (String) tblRoom.getValueAt(selectedRow, 1);
        String roomType = (String) tblRoom.getValueAt(selectedRow, 2);
        
        // Populate text fields with selected room details
        txtRoomNumber.setText(roomNumber);
        txtRoomType.setText(roomType);
    }
    }//GEN-LAST:event_tblRoomMouseClicked

    private void btnBookNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookNowActionPerformed
        String roomNumberStr = txtRoomNumber.getText().trim();
    String roomType = txtRoomType.getText().trim();
    
    if (!roomNumberStr.isEmpty() && !roomType.isEmpty()) {
        try {
            // Convert room number from String to int
            int roomNumber = Integer.parseInt(roomNumberStr);
            
            // Open the reservation page and pass room details
            Reservations reservation = new Reservations(roomNumber, roomType);
            reservation.setVisible(true);
            this.dispose(); // Close the search room page if needed
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid room number format.", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select a room first.", "Selection Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnBookNowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Room().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvailableRooms;
    private javax.swing.JButton btnBookNow;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbRoomType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRoom;
    private app.bolivia.swing.JCTextField txtRoomNumber;
    private app.bolivia.swing.JCTextField txtRoomType;
    // End of variables declaration//GEN-END:variables
}
